name: Build Android APK (Buildozer)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build APK with Docker
        run: |
          # Проверяем наличие конфига перед сборкой (для отладки в логах Гитхаба)
          ls -R res/xml/
          
          docker run --rm \
            -v "${{ github.workspace }}:/home/user/hostcwd" \
            -w /home/user/hostcwd \
            kivy/buildozer:latest \
            android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: bin/*.apk
